version: '3.5'
services:
  ui:
    build: ui
    expose:
      - "4200"
    ports:
      - "4200:80"
    hostname: "gek.ui"
    container_name: 'gek-ui'
    networks:
    - "gek"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: gek-ui

  server:
    build: server
    expose:
      - "3000"
      - "8080"
    ports:
      - "3000:3000"
      - "8080:8080"
    hostname: 'gek.server'
    container_name: 'gek-server'
    networks:
    - "gek"
    dns:
    - 8.8.8.8
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: gek-server
#    env_file: ../.env

networks:
  gek:
    name: proxy-manager
    external: true
