version: '3.5'
services:
  ui:
    build: ui
    expose:
      - "4200"
    ports:
      - "4200:80"
    hostname: "gek.ui"
    container_name: 'gek-ui'
    networks:
    - "default"
    restart: unless-stopped

  server:
    build: server
    expose:
      - "3000"
      - "8080"
    ports:
      - "3000:3000"
      - "8080:8080"
    hostname: 'gek.server'
    container_name: 'gek-server'
    dns:
      - 8.8.8.8  # Google's DNS
      - 8.8.4.4  # Secondary Google's DNS
    networks:
    - "default"
    restart: unless-stopped
#    env_file: ../.env

networks:
  default:
    name: proxy-manager
    external: true
